language: node_js
node_js:
  - "6"
script:
  - npm test
after_success:
  - npm install codeclimate-test-reporter -g
  - npm run coverage
addons:
    code_climate:
        repo_token:  398c255ac3c33e25597c49ae6d9bedf3cf961bff5aa1cb9366afc98693794368

